dist: xenial
language: python
services: docker

python:
  - "2.7"
  - "3.6"
  - "3.7"

env:
  global:
    - ROLE_NAME=docker
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv tox-travis
  - pipenv install --dev

script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/