---
- name: Vars
  include: vars.yml

- name:
  include: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "install-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "install-{{ ansible_distribution }}.yml"
        - "install-{{ ansible_os_family }}.yml"
        - "install.yml"
      paths:
        - 'tasks'


- name: Start daemon
  service:
    name: "{{ cron_daemon }}"
    state: started
    enabled: yes

- name: "Add cron"
  become: yes
  cron:
    job: "{{ item.command.replace('%', '\\%') }}"
    name: "{{ item.name }}"

    minute: "{{ item.minute|default('*') }}"
    hour: "{{ item.hour|default('*') }}"
    day: "{{ item.day|default('*') }}"
    month: "{{ item.month|default('*') }}"
    weekday: "{{ item.weekday|default('*') }}"
    user: "{{ item.user|default(ansible_ssh_user) }}"

    state: present

  with_items: [ "{{ cron }}" ]
  when: (
        item.delete is undefined
        or (item.delete is defined and not item.delete)
          )

- name: "Remove cron"
  become: yes
  cron:
    name: "{{ item.name }}"
    user: "{{ item.user|default(ansible_ssh_user) }}"
    state: absent

  with_items: [ "{{ cron }}" ]
  when: item.delete is defined and item.delete
