---

- name: Converge
  hosts: all
  vars:
    # Default user
    ansible_ssh_user: root
    cron:
      - name: example
        command: /bin/echo %100%
        # defaults
        minute: "0"
        hour: "1"
        day: "2"
        month: "3"
        weekday: "4"

      - name: for remove
        delete: true

  roles:
    - role: ansible-role-cron
